name: BeachBrake Coaching
favicon: null
layout_spectrum: 0.00073
typography_spectrum: 0.72037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff6f7'
    - '#d0c892'
    - '#00bccc'
    - '#8d8c53'
    - '#ec9e7d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
