name: BeachBrake Coaching
favicon: null
layout_spectrum: 0.99916
typography_spectrum: 0.75167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3d2a2c'
    - '#d99d83'
    - '#a55a30'
    - '#00a5e2'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
