name: BeachBrake Coaching
favicon: null
layout_spectrum: 0.24624
typography_spectrum: 0.69397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b0d2de'
    - '#5fa6d3'
    - '#bb9158'
    - '#010206'
    - '#005575'
  brandStrength: 0.5
  lightness: 0.34885041252709925
  saturation: 0.625
  rhythmicContrast: 0.432598733343184
purpose: []
